[build]
  publish = "dist"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "yarn dev"
  port = 5173